Feat/elo system
YuriAlessandro/peladaManager pull request #4
Opened 2024-09-20 19:06 UTC by isaacbatst

## Alterações:

1.  Adiciona `LOCAL_STORAGE_ELO_KEY` para salvar um objeto com nome dos jogadores -> elo 
    - `{ "isaac": { ... }, "yuri": { ... } }`
2. `onDocumentReady`: se não tiver dados dos elos no storage, inicializa todos os jogadores do histórico com um elo inicial.
3. `$("#add-new-player").click`: adiciona jogador ao sistema de elo.
4. Seta `type="module"` no `<script>` para importar arquivos separados  
5. Adiciona módulo de Elo `elo.js` usando o [True System](https://www.microsoft.com/en-us/research/project/trueskill-ranking-system/), com a implementação da lib [ts-trueskill](https://github.com/scttcper/ts-trueskill) em `lib/true-skill/bundle.js`
    - Exporta 3 funções:
      - `createInitialRating`: cria o elo inicial de um jogador novo
      - `findBestTeamMatch`: recebe uma lista de jogadores e retorna a divisão mais equilibrada
      - `updateRatings`: recebe o time vencedor e o time perdedor e retorna seus elos atualizados
      
 
## Sistema de Elo:
        
O algoritmo usa dois valores:
-  `mu`: indica o elo do jogador
    - Valor inicial: `25` 
    - Aumenta se o jogador ganha, diminui se o jogador perde 😮, levando em consideração o elo do seu time e do time adversário. 
- `sigma`: indica o grau de incerteza do sistema que `mu` é realmente o elo do jogador
     - Valor inicial `8.3`
     - Diminui conforme o jogador joga, principalmente quando ganha E perde

## Matchmaking

É usado o conceito de `quality` que considera tanto o `mu`, quanto o `sigma` de todos os jogadores para calcular a melhor distribuição possível de times.

2024-09-20 23:13 UTC, YuriAlessandro requested changes

2024-09-20 23:13 UTC, YuriAlessandro commented on index.html
> +        <!-- create bulma div space between flex row -->
Remover

2024-09-20 23:13 UTC, YuriAlessandro commented on index.js
>  function generateRandomTeams(players) {
Muda para `generateTeams`

2024-09-20 23:13 UTC, YuriAlessandro commented on index.html
> +        <!-- checkbox for dev mode, use font awesome code icon -->
Remover

2024-09-21 15:06 UTC, isaacbatst commented on index.html
> +        <!-- create bulma div space between flex row -->
hauha só os comentário pro copilot

2024-09-21 15:07 UTC, isaacbatst commented on index.html
> +        <!-- checkbox for dev mode, use font awesome code icon -->
```suggestion
```

2024-09-21 15:07 UTC, isaacbatst commented on index.html
> +        <!-- checkbox for dev mode, use font awesome code icon -->
```suggestion
```

2024-09-21 15:08 UTC, isaacbatst commented on index.html
> +        <!-- create bulma div space between flex row -->
```suggestion
```

2024-09-21 15:08 UTC, isaacbatst commented on index.js
>  function generateRandomTeams(players) {
faz sentido

2024-09-21 19:37 UTC, merged